name: Testing Github Actions!
run-name: ${{github.actor}} Testing Github Actions!
on:
  push:
    branches:
      - actions-test
jobs:
  main-job:
    name: The Main Job Yo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform Action
        uses: hashicorp/setup-terraform@v3
      - name: Run Terraform
        run: |
          cd terraform
          terraform init
          export TF_VAR_project_id=gcp-practice-1-453919
          export TF_VAR_region=us-east1
          export TF_VAR_zone=us-east1-b
          export TF_VAR_external_ip=0.0.0.0
          export TF_VAR_domain_name=audiobytes.app
          terraform plan
