name: Testing Github Actions!
run-name: ${{github.actor}} Testing Github Actions!
on:
  push:
    branches:
      - actions-test
jobs:
  main-job:
    name: The Main Job Yo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List the files
        run: ls -la
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Test Terraform
        run: |
          terraform init
          ls -la
