name: Testing Github Actions!
run-name: ${{github.actor}} Testing Github Actions!
on:
  push:
    branches:
      - actions-test
jobs:
  main-job:
    name: The Main Job Yo
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing to see if this works!"
      - name: Testing Name
        run: echo "This is a ${{github.event}}"
